// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.3
// source: mesh.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HardwareModel int32

const (
	HardwareModel_UNSET                        HardwareModel = 0
	HardwareModel_TLORA_V2                     HardwareModel = 1
	HardwareModel_TLORA_V1                     HardwareModel = 2
	HardwareModel_TLORA_V2_1_1P6               HardwareModel = 3
	HardwareModel_TBEAM                        HardwareModel = 4
	HardwareModel_HELTEC_V2_0                  HardwareModel = 5
	HardwareModel_TBEAM_V0P7                   HardwareModel = 6
	HardwareModel_T_ECHO                       HardwareModel = 7
	HardwareModel_TLORA_V1_1P3                 HardwareModel = 8
	HardwareModel_RAK4631                      HardwareModel = 9
	HardwareModel_HELTEC_V2_1                  HardwareModel = 10
	HardwareModel_HELTEC_V1                    HardwareModel = 11
	HardwareModel_LILYGO_TBEAM_S3_CORE         HardwareModel = 12
	HardwareModel_RAK11200                     HardwareModel = 13
	HardwareModel_NANO_G1                      HardwareModel = 14
	HardwareModel_TLORA_V2_1_1P8               HardwareModel = 15
	HardwareModel_TLORA_T3_S3                  HardwareModel = 16
	HardwareModel_NANO_G1_EXPLORER             HardwareModel = 17
	HardwareModel_NANO_G2_ULTRA                HardwareModel = 18
	HardwareModel_LORA_TYPE                    HardwareModel = 19
	HardwareModel_WIPHONE                      HardwareModel = 20
	HardwareModel_WIO_WM1110                   HardwareModel = 21
	HardwareModel_RAK2560                      HardwareModel = 22
	HardwareModel_HELTEC_HRU_3601              HardwareModel = 23
	HardwareModel_HELTEC_WIRELESS_BRIDGE       HardwareModel = 24
	HardwareModel_STATION_G1                   HardwareModel = 25
	HardwareModel_RAK11310                     HardwareModel = 26
	HardwareModel_SENSELORA_RP2040             HardwareModel = 27
	HardwareModel_SENSELORA_S3                 HardwareModel = 28
	HardwareModel_CANARYONE                    HardwareModel = 29
	HardwareModel_RP2040_LORA                  HardwareModel = 30
	HardwareModel_STATION_G2                   HardwareModel = 31
	HardwareModel_LORA_RELAY_V1                HardwareModel = 32
	HardwareModel_NRF52840DK                   HardwareModel = 33
	HardwareModel_PPR                          HardwareModel = 34
	HardwareModel_GENIEBLOCKS                  HardwareModel = 35
	HardwareModel_NRF52_UNKNOWN                HardwareModel = 36
	HardwareModel_PORTDUINO                    HardwareModel = 37
	HardwareModel_ANDROID_SIM                  HardwareModel = 38
	HardwareModel_DIY_V1                       HardwareModel = 39
	HardwareModel_NRF52840_PCA10059            HardwareModel = 40
	HardwareModel_DR_DEV                       HardwareModel = 41
	HardwareModel_M5STACK                      HardwareModel = 42
	HardwareModel_HELTEC_V3                    HardwareModel = 43
	HardwareModel_HELTEC_WSL_V3                HardwareModel = 44
	HardwareModel_BETAFPV_2400_TX              HardwareModel = 45
	HardwareModel_BETAFPV_900_NANO_TX          HardwareModel = 46
	HardwareModel_RPI_PICO                     HardwareModel = 47
	HardwareModel_HELTEC_WIRELESS_TRACKER      HardwareModel = 48
	HardwareModel_HELTEC_WIRELESS_PAPER        HardwareModel = 49
	HardwareModel_T_DECK                       HardwareModel = 50
	HardwareModel_T_WATCH_S3                   HardwareModel = 51
	HardwareModel_PICOMPUTER_S3                HardwareModel = 52
	HardwareModel_HELTEC_HT62                  HardwareModel = 53
	HardwareModel_EBYTE_ESP32_S3               HardwareModel = 54
	HardwareModel_ESP32_S3_PICO                HardwareModel = 55
	HardwareModel_CHATTER_2                    HardwareModel = 56
	HardwareModel_HELTEC_WIRELESS_PAPER_V1_0   HardwareModel = 57
	HardwareModel_HELTEC_WIRELESS_TRACKER_V1_0 HardwareModel = 58
	HardwareModel_UNPHONE                      HardwareModel = 59
	HardwareModel_TD_LORAC                     HardwareModel = 60
	HardwareModel_CDEBYTE_EORA_S3              HardwareModel = 61
	HardwareModel_TWC_MESH_V4                  HardwareModel = 62
	HardwareModel_NRF52_PROMICRO_DIY           HardwareModel = 63
	HardwareModel_RADIOMASTER_900_BANDIT_NANO  HardwareModel = 64
	HardwareModel_HELTEC_CAPSULE_SENSOR_V3     HardwareModel = 65
	HardwareModel_HELTEC_VISION_MASTER_T190    HardwareModel = 66
	HardwareModel_HELTEC_VISION_MASTER_E213    HardwareModel = 67
	HardwareModel_HELTEC_VISION_MASTER_E290    HardwareModel = 68
	HardwareModel_HELTEC_MESH_NODE_T114        HardwareModel = 69
	HardwareModel_SENSECAP_INDICATOR           HardwareModel = 70
	HardwareModel_TRACKER_T1000_E              HardwareModel = 71
	HardwareModel_RAK3172                      HardwareModel = 72
	HardwareModel_WIO_E5                       HardwareModel = 73
	HardwareModel_RADIOMASTER_900_BANDIT       HardwareModel = 74
	HardwareModel_PRIVATE_HW                   HardwareModel = 255
)

// Enum value maps for HardwareModel.
var (
	HardwareModel_name = map[int32]string{
		0:   "UNSET",
		1:   "TLORA_V2",
		2:   "TLORA_V1",
		3:   "TLORA_V2_1_1P6",
		4:   "TBEAM",
		5:   "HELTEC_V2_0",
		6:   "TBEAM_V0P7",
		7:   "T_ECHO",
		8:   "TLORA_V1_1P3",
		9:   "RAK4631",
		10:  "HELTEC_V2_1",
		11:  "HELTEC_V1",
		12:  "LILYGO_TBEAM_S3_CORE",
		13:  "RAK11200",
		14:  "NANO_G1",
		15:  "TLORA_V2_1_1P8",
		16:  "TLORA_T3_S3",
		17:  "NANO_G1_EXPLORER",
		18:  "NANO_G2_ULTRA",
		19:  "LORA_TYPE",
		20:  "WIPHONE",
		21:  "WIO_WM1110",
		22:  "RAK2560",
		23:  "HELTEC_HRU_3601",
		24:  "HELTEC_WIRELESS_BRIDGE",
		25:  "STATION_G1",
		26:  "RAK11310",
		27:  "SENSELORA_RP2040",
		28:  "SENSELORA_S3",
		29:  "CANARYONE",
		30:  "RP2040_LORA",
		31:  "STATION_G2",
		32:  "LORA_RELAY_V1",
		33:  "NRF52840DK",
		34:  "PPR",
		35:  "GENIEBLOCKS",
		36:  "NRF52_UNKNOWN",
		37:  "PORTDUINO",
		38:  "ANDROID_SIM",
		39:  "DIY_V1",
		40:  "NRF52840_PCA10059",
		41:  "DR_DEV",
		42:  "M5STACK",
		43:  "HELTEC_V3",
		44:  "HELTEC_WSL_V3",
		45:  "BETAFPV_2400_TX",
		46:  "BETAFPV_900_NANO_TX",
		47:  "RPI_PICO",
		48:  "HELTEC_WIRELESS_TRACKER",
		49:  "HELTEC_WIRELESS_PAPER",
		50:  "T_DECK",
		51:  "T_WATCH_S3",
		52:  "PICOMPUTER_S3",
		53:  "HELTEC_HT62",
		54:  "EBYTE_ESP32_S3",
		55:  "ESP32_S3_PICO",
		56:  "CHATTER_2",
		57:  "HELTEC_WIRELESS_PAPER_V1_0",
		58:  "HELTEC_WIRELESS_TRACKER_V1_0",
		59:  "UNPHONE",
		60:  "TD_LORAC",
		61:  "CDEBYTE_EORA_S3",
		62:  "TWC_MESH_V4",
		63:  "NRF52_PROMICRO_DIY",
		64:  "RADIOMASTER_900_BANDIT_NANO",
		65:  "HELTEC_CAPSULE_SENSOR_V3",
		66:  "HELTEC_VISION_MASTER_T190",
		67:  "HELTEC_VISION_MASTER_E213",
		68:  "HELTEC_VISION_MASTER_E290",
		69:  "HELTEC_MESH_NODE_T114",
		70:  "SENSECAP_INDICATOR",
		71:  "TRACKER_T1000_E",
		72:  "RAK3172",
		73:  "WIO_E5",
		74:  "RADIOMASTER_900_BANDIT",
		255: "PRIVATE_HW",
	}
	HardwareModel_value = map[string]int32{
		"UNSET":                        0,
		"TLORA_V2":                     1,
		"TLORA_V1":                     2,
		"TLORA_V2_1_1P6":               3,
		"TBEAM":                        4,
		"HELTEC_V2_0":                  5,
		"TBEAM_V0P7":                   6,
		"T_ECHO":                       7,
		"TLORA_V1_1P3":                 8,
		"RAK4631":                      9,
		"HELTEC_V2_1":                  10,
		"HELTEC_V1":                    11,
		"LILYGO_TBEAM_S3_CORE":         12,
		"RAK11200":                     13,
		"NANO_G1":                      14,
		"TLORA_V2_1_1P8":               15,
		"TLORA_T3_S3":                  16,
		"NANO_G1_EXPLORER":             17,
		"NANO_G2_ULTRA":                18,
		"LORA_TYPE":                    19,
		"WIPHONE":                      20,
		"WIO_WM1110":                   21,
		"RAK2560":                      22,
		"HELTEC_HRU_3601":              23,
		"HELTEC_WIRELESS_BRIDGE":       24,
		"STATION_G1":                   25,
		"RAK11310":                     26,
		"SENSELORA_RP2040":             27,
		"SENSELORA_S3":                 28,
		"CANARYONE":                    29,
		"RP2040_LORA":                  30,
		"STATION_G2":                   31,
		"LORA_RELAY_V1":                32,
		"NRF52840DK":                   33,
		"PPR":                          34,
		"GENIEBLOCKS":                  35,
		"NRF52_UNKNOWN":                36,
		"PORTDUINO":                    37,
		"ANDROID_SIM":                  38,
		"DIY_V1":                       39,
		"NRF52840_PCA10059":            40,
		"DR_DEV":                       41,
		"M5STACK":                      42,
		"HELTEC_V3":                    43,
		"HELTEC_WSL_V3":                44,
		"BETAFPV_2400_TX":              45,
		"BETAFPV_900_NANO_TX":          46,
		"RPI_PICO":                     47,
		"HELTEC_WIRELESS_TRACKER":      48,
		"HELTEC_WIRELESS_PAPER":        49,
		"T_DECK":                       50,
		"T_WATCH_S3":                   51,
		"PICOMPUTER_S3":                52,
		"HELTEC_HT62":                  53,
		"EBYTE_ESP32_S3":               54,
		"ESP32_S3_PICO":                55,
		"CHATTER_2":                    56,
		"HELTEC_WIRELESS_PAPER_V1_0":   57,
		"HELTEC_WIRELESS_TRACKER_V1_0": 58,
		"UNPHONE":                      59,
		"TD_LORAC":                     60,
		"CDEBYTE_EORA_S3":              61,
		"TWC_MESH_V4":                  62,
		"NRF52_PROMICRO_DIY":           63,
		"RADIOMASTER_900_BANDIT_NANO":  64,
		"HELTEC_CAPSULE_SENSOR_V3":     65,
		"HELTEC_VISION_MASTER_T190":    66,
		"HELTEC_VISION_MASTER_E213":    67,
		"HELTEC_VISION_MASTER_E290":    68,
		"HELTEC_MESH_NODE_T114":        69,
		"SENSECAP_INDICATOR":           70,
		"TRACKER_T1000_E":              71,
		"RAK3172":                      72,
		"WIO_E5":                       73,
		"RADIOMASTER_900_BANDIT":       74,
		"PRIVATE_HW":                   255,
	}
)

func (x HardwareModel) Enum() *HardwareModel {
	p := new(HardwareModel)
	*p = x
	return p
}

func (x HardwareModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HardwareModel) Descriptor() protoreflect.EnumDescriptor {
	return file_mesh_proto_enumTypes[0].Descriptor()
}

func (HardwareModel) Type() protoreflect.EnumType {
	return &file_mesh_proto_enumTypes[0]
}

func (x HardwareModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HardwareModel.Descriptor instead.
func (HardwareModel) EnumDescriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

type Position_LocSource int32

const (
	Position_LOC_UNSET    Position_LocSource = 0
	Position_LOC_MANUAL   Position_LocSource = 1
	Position_LOC_INTERNAL Position_LocSource = 2
	Position_LOC_EXTERNAL Position_LocSource = 3
)

// Enum value maps for Position_LocSource.
var (
	Position_LocSource_name = map[int32]string{
		0: "LOC_UNSET",
		1: "LOC_MANUAL",
		2: "LOC_INTERNAL",
		3: "LOC_EXTERNAL",
	}
	Position_LocSource_value = map[string]int32{
		"LOC_UNSET":    0,
		"LOC_MANUAL":   1,
		"LOC_INTERNAL": 2,
		"LOC_EXTERNAL": 3,
	}
)

func (x Position_LocSource) Enum() *Position_LocSource {
	p := new(Position_LocSource)
	*p = x
	return p
}

func (x Position_LocSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Position_LocSource) Descriptor() protoreflect.EnumDescriptor {
	return file_mesh_proto_enumTypes[1].Descriptor()
}

func (Position_LocSource) Type() protoreflect.EnumType {
	return &file_mesh_proto_enumTypes[1]
}

func (x Position_LocSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Position_LocSource.Descriptor instead.
func (Position_LocSource) EnumDescriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0, 0}
}

type Position_AltSource int32

const (
	Position_ALT_UNSET      Position_AltSource = 0
	Position_ALT_MANUAL     Position_AltSource = 1
	Position_ALT_INTERNAL   Position_AltSource = 2
	Position_ALT_EXTERNAL   Position_AltSource = 3
	Position_ALT_BAROMETRIC Position_AltSource = 4
)

// Enum value maps for Position_AltSource.
var (
	Position_AltSource_name = map[int32]string{
		0: "ALT_UNSET",
		1: "ALT_MANUAL",
		2: "ALT_INTERNAL",
		3: "ALT_EXTERNAL",
		4: "ALT_BAROMETRIC",
	}
	Position_AltSource_value = map[string]int32{
		"ALT_UNSET":      0,
		"ALT_MANUAL":     1,
		"ALT_INTERNAL":   2,
		"ALT_EXTERNAL":   3,
		"ALT_BAROMETRIC": 4,
	}
)

func (x Position_AltSource) Enum() *Position_AltSource {
	p := new(Position_AltSource)
	*p = x
	return p
}

func (x Position_AltSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Position_AltSource) Descriptor() protoreflect.EnumDescriptor {
	return file_mesh_proto_enumTypes[2].Descriptor()
}

func (Position_AltSource) Type() protoreflect.EnumType {
	return &file_mesh_proto_enumTypes[2]
}

func (x Position_AltSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Position_AltSource.Descriptor instead.
func (Position_AltSource) EnumDescriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0, 1}
}

type Position struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	LatitudeI                 *int32                 `protobuf:"fixed32,1,opt,name=latitude_i,json=latitudeI,proto3,oneof" json:"latitude_i,omitempty"`
	LongitudeI                *int32                 `protobuf:"fixed32,2,opt,name=longitude_i,json=longitudeI,proto3,oneof" json:"longitude_i,omitempty"`
	Altitude                  *int32                 `protobuf:"varint,3,opt,name=altitude,proto3,oneof" json:"altitude,omitempty"`
	Time                      uint32                 `protobuf:"fixed32,4,opt,name=time,proto3" json:"time,omitempty"`
	LocationSource            Position_LocSource     `protobuf:"varint,5,opt,name=location_source,json=locationSource,proto3,enum=meshtastic.Position_LocSource" json:"location_source,omitempty"`
	AltitudeSource            Position_AltSource     `protobuf:"varint,6,opt,name=altitude_source,json=altitudeSource,proto3,enum=meshtastic.Position_AltSource" json:"altitude_source,omitempty"`
	Timestamp                 uint32                 `protobuf:"fixed32,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TimestampMillisAdjust     int32                  `protobuf:"varint,8,opt,name=timestamp_millis_adjust,json=timestampMillisAdjust,proto3" json:"timestamp_millis_adjust,omitempty"`
	AltitudeHae               *int32                 `protobuf:"zigzag32,9,opt,name=altitude_hae,json=altitudeHae,proto3,oneof" json:"altitude_hae,omitempty"`
	AltitudeGeoidalSeparation *int32                 `protobuf:"zigzag32,10,opt,name=altitude_geoidal_separation,json=altitudeGeoidalSeparation,proto3,oneof" json:"altitude_geoidal_separation,omitempty"`
	PDOP                      uint32                 `protobuf:"varint,11,opt,name=PDOP,proto3" json:"PDOP,omitempty"`
	HDOP                      uint32                 `protobuf:"varint,12,opt,name=HDOP,proto3" json:"HDOP,omitempty"`
	VDOP                      uint32                 `protobuf:"varint,13,opt,name=VDOP,proto3" json:"VDOP,omitempty"`
	GpsAccuracy               uint32                 `protobuf:"varint,14,opt,name=gps_accuracy,json=gpsAccuracy,proto3" json:"gps_accuracy,omitempty"`
	GroundSpeed               *uint32                `protobuf:"varint,15,opt,name=ground_speed,json=groundSpeed,proto3,oneof" json:"ground_speed,omitempty"`
	GroundTrack               *uint32                `protobuf:"varint,16,opt,name=ground_track,json=groundTrack,proto3,oneof" json:"ground_track,omitempty"`
	FixQuality                uint32                 `protobuf:"varint,17,opt,name=fix_quality,json=fixQuality,proto3" json:"fix_quality,omitempty"`
	FixType                   uint32                 `protobuf:"varint,18,opt,name=fix_type,json=fixType,proto3" json:"fix_type,omitempty"`
	SatsInView                uint32                 `protobuf:"varint,19,opt,name=sats_in_view,json=satsInView,proto3" json:"sats_in_view,omitempty"`
	SensorId                  uint32                 `protobuf:"varint,20,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	NextUpdate                uint32                 `protobuf:"varint,21,opt,name=next_update,json=nextUpdate,proto3" json:"next_update,omitempty"`
	SeqNumber                 uint32                 `protobuf:"varint,22,opt,name=seq_number,json=seqNumber,proto3" json:"seq_number,omitempty"`
	PrecisionBits             uint32                 `protobuf:"varint,23,opt,name=precision_bits,json=precisionBits,proto3" json:"precision_bits,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetLatitudeI() int32 {
	if x != nil && x.LatitudeI != nil {
		return *x.LatitudeI
	}
	return 0
}

func (x *Position) GetLongitudeI() int32 {
	if x != nil && x.LongitudeI != nil {
		return *x.LongitudeI
	}
	return 0
}

func (x *Position) GetAltitude() int32 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

func (x *Position) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Position) GetLocationSource() Position_LocSource {
	if x != nil {
		return x.LocationSource
	}
	return Position_LOC_UNSET
}

func (x *Position) GetAltitudeSource() Position_AltSource {
	if x != nil {
		return x.AltitudeSource
	}
	return Position_ALT_UNSET
}

func (x *Position) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Position) GetTimestampMillisAdjust() int32 {
	if x != nil {
		return x.TimestampMillisAdjust
	}
	return 0
}

func (x *Position) GetAltitudeHae() int32 {
	if x != nil && x.AltitudeHae != nil {
		return *x.AltitudeHae
	}
	return 0
}

func (x *Position) GetAltitudeGeoidalSeparation() int32 {
	if x != nil && x.AltitudeGeoidalSeparation != nil {
		return *x.AltitudeGeoidalSeparation
	}
	return 0
}

func (x *Position) GetPDOP() uint32 {
	if x != nil {
		return x.PDOP
	}
	return 0
}

func (x *Position) GetHDOP() uint32 {
	if x != nil {
		return x.HDOP
	}
	return 0
}

func (x *Position) GetVDOP() uint32 {
	if x != nil {
		return x.VDOP
	}
	return 0
}

func (x *Position) GetGpsAccuracy() uint32 {
	if x != nil {
		return x.GpsAccuracy
	}
	return 0
}

func (x *Position) GetGroundSpeed() uint32 {
	if x != nil && x.GroundSpeed != nil {
		return *x.GroundSpeed
	}
	return 0
}

func (x *Position) GetGroundTrack() uint32 {
	if x != nil && x.GroundTrack != nil {
		return *x.GroundTrack
	}
	return 0
}

func (x *Position) GetFixQuality() uint32 {
	if x != nil {
		return x.FixQuality
	}
	return 0
}

func (x *Position) GetFixType() uint32 {
	if x != nil {
		return x.FixType
	}
	return 0
}

func (x *Position) GetSatsInView() uint32 {
	if x != nil {
		return x.SatsInView
	}
	return 0
}

func (x *Position) GetSensorId() uint32 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *Position) GetNextUpdate() uint32 {
	if x != nil {
		return x.NextUpdate
	}
	return 0
}

func (x *Position) GetSeqNumber() uint32 {
	if x != nil {
		return x.SeqNumber
	}
	return 0
}

func (x *Position) GetPrecisionBits() uint32 {
	if x != nil {
		return x.PrecisionBits
	}
	return 0
}

var File_mesh_proto protoreflect.FileDescriptor

const file_mesh_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mesh.proto\x12\n" +
	"meshtastic\"\xa2\t\n" +
	"\bPosition\x12\"\n" +
	"\n" +
	"latitude_i\x18\x01 \x01(\x0fH\x00R\tlatitudeI\x88\x01\x01\x12$\n" +
	"\vlongitude_i\x18\x02 \x01(\x0fH\x01R\n" +
	"longitudeI\x88\x01\x01\x12\x1f\n" +
	"\baltitude\x18\x03 \x01(\x05H\x02R\baltitude\x88\x01\x01\x12\x12\n" +
	"\x04time\x18\x04 \x01(\aR\x04time\x12G\n" +
	"\x0flocation_source\x18\x05 \x01(\x0e2\x1e.meshtastic.Position.LocSourceR\x0elocationSource\x12G\n" +
	"\x0faltitude_source\x18\x06 \x01(\x0e2\x1e.meshtastic.Position.AltSourceR\x0ealtitudeSource\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\aR\ttimestamp\x126\n" +
	"\x17timestamp_millis_adjust\x18\b \x01(\x05R\x15timestampMillisAdjust\x12&\n" +
	"\faltitude_hae\x18\t \x01(\x11H\x03R\valtitudeHae\x88\x01\x01\x12C\n" +
	"\x1baltitude_geoidal_separation\x18\n" +
	" \x01(\x11H\x04R\x19altitudeGeoidalSeparation\x88\x01\x01\x12\x12\n" +
	"\x04PDOP\x18\v \x01(\rR\x04PDOP\x12\x12\n" +
	"\x04HDOP\x18\f \x01(\rR\x04HDOP\x12\x12\n" +
	"\x04VDOP\x18\r \x01(\rR\x04VDOP\x12!\n" +
	"\fgps_accuracy\x18\x0e \x01(\rR\vgpsAccuracy\x12&\n" +
	"\fground_speed\x18\x0f \x01(\rH\x05R\vgroundSpeed\x88\x01\x01\x12&\n" +
	"\fground_track\x18\x10 \x01(\rH\x06R\vgroundTrack\x88\x01\x01\x12\x1f\n" +
	"\vfix_quality\x18\x11 \x01(\rR\n" +
	"fixQuality\x12\x19\n" +
	"\bfix_type\x18\x12 \x01(\rR\afixType\x12 \n" +
	"\fsats_in_view\x18\x13 \x01(\rR\n" +
	"satsInView\x12\x1b\n" +
	"\tsensor_id\x18\x14 \x01(\rR\bsensorId\x12\x1f\n" +
	"\vnext_update\x18\x15 \x01(\rR\n" +
	"nextUpdate\x12\x1d\n" +
	"\n" +
	"seq_number\x18\x16 \x01(\rR\tseqNumber\x12%\n" +
	"\x0eprecision_bits\x18\x17 \x01(\rR\rprecisionBits\"N\n" +
	"\tLocSource\x12\r\n" +
	"\tLOC_UNSET\x10\x00\x12\x0e\n" +
	"\n" +
	"LOC_MANUAL\x10\x01\x12\x10\n" +
	"\fLOC_INTERNAL\x10\x02\x12\x10\n" +
	"\fLOC_EXTERNAL\x10\x03\"b\n" +
	"\tAltSource\x12\r\n" +
	"\tALT_UNSET\x10\x00\x12\x0e\n" +
	"\n" +
	"ALT_MANUAL\x10\x01\x12\x10\n" +
	"\fALT_INTERNAL\x10\x02\x12\x10\n" +
	"\fALT_EXTERNAL\x10\x03\x12\x12\n" +
	"\x0eALT_BAROMETRIC\x10\x04B\r\n" +
	"\v_latitude_iB\x0e\n" +
	"\f_longitude_iB\v\n" +
	"\t_altitudeB\x0f\n" +
	"\r_altitude_haeB\x1e\n" +
	"\x1c_altitude_geoidal_separationB\x0f\n" +
	"\r_ground_speedB\x0f\n" +
	"\r_ground_track*\xa1\v\n" +
	"\rHardwareModel\x12\t\n" +
	"\x05UNSET\x10\x00\x12\f\n" +
	"\bTLORA_V2\x10\x01\x12\f\n" +
	"\bTLORA_V1\x10\x02\x12\x12\n" +
	"\x0eTLORA_V2_1_1P6\x10\x03\x12\t\n" +
	"\x05TBEAM\x10\x04\x12\x0f\n" +
	"\vHELTEC_V2_0\x10\x05\x12\x0e\n" +
	"\n" +
	"TBEAM_V0P7\x10\x06\x12\n" +
	"\n" +
	"\x06T_ECHO\x10\a\x12\x10\n" +
	"\fTLORA_V1_1P3\x10\b\x12\v\n" +
	"\aRAK4631\x10\t\x12\x0f\n" +
	"\vHELTEC_V2_1\x10\n" +
	"\x12\r\n" +
	"\tHELTEC_V1\x10\v\x12\x18\n" +
	"\x14LILYGO_TBEAM_S3_CORE\x10\f\x12\f\n" +
	"\bRAK11200\x10\r\x12\v\n" +
	"\aNANO_G1\x10\x0e\x12\x12\n" +
	"\x0eTLORA_V2_1_1P8\x10\x0f\x12\x0f\n" +
	"\vTLORA_T3_S3\x10\x10\x12\x14\n" +
	"\x10NANO_G1_EXPLORER\x10\x11\x12\x11\n" +
	"\rNANO_G2_ULTRA\x10\x12\x12\r\n" +
	"\tLORA_TYPE\x10\x13\x12\v\n" +
	"\aWIPHONE\x10\x14\x12\x0e\n" +
	"\n" +
	"WIO_WM1110\x10\x15\x12\v\n" +
	"\aRAK2560\x10\x16\x12\x13\n" +
	"\x0fHELTEC_HRU_3601\x10\x17\x12\x1a\n" +
	"\x16HELTEC_WIRELESS_BRIDGE\x10\x18\x12\x0e\n" +
	"\n" +
	"STATION_G1\x10\x19\x12\f\n" +
	"\bRAK11310\x10\x1a\x12\x14\n" +
	"\x10SENSELORA_RP2040\x10\x1b\x12\x10\n" +
	"\fSENSELORA_S3\x10\x1c\x12\r\n" +
	"\tCANARYONE\x10\x1d\x12\x0f\n" +
	"\vRP2040_LORA\x10\x1e\x12\x0e\n" +
	"\n" +
	"STATION_G2\x10\x1f\x12\x11\n" +
	"\rLORA_RELAY_V1\x10 \x12\x0e\n" +
	"\n" +
	"NRF52840DK\x10!\x12\a\n" +
	"\x03PPR\x10\"\x12\x0f\n" +
	"\vGENIEBLOCKS\x10#\x12\x11\n" +
	"\rNRF52_UNKNOWN\x10$\x12\r\n" +
	"\tPORTDUINO\x10%\x12\x0f\n" +
	"\vANDROID_SIM\x10&\x12\n" +
	"\n" +
	"\x06DIY_V1\x10'\x12\x15\n" +
	"\x11NRF52840_PCA10059\x10(\x12\n" +
	"\n" +
	"\x06DR_DEV\x10)\x12\v\n" +
	"\aM5STACK\x10*\x12\r\n" +
	"\tHELTEC_V3\x10+\x12\x11\n" +
	"\rHELTEC_WSL_V3\x10,\x12\x13\n" +
	"\x0fBETAFPV_2400_TX\x10-\x12\x17\n" +
	"\x13BETAFPV_900_NANO_TX\x10.\x12\f\n" +
	"\bRPI_PICO\x10/\x12\x1b\n" +
	"\x17HELTEC_WIRELESS_TRACKER\x100\x12\x19\n" +
	"\x15HELTEC_WIRELESS_PAPER\x101\x12\n" +
	"\n" +
	"\x06T_DECK\x102\x12\x0e\n" +
	"\n" +
	"T_WATCH_S3\x103\x12\x11\n" +
	"\rPICOMPUTER_S3\x104\x12\x0f\n" +
	"\vHELTEC_HT62\x105\x12\x12\n" +
	"\x0eEBYTE_ESP32_S3\x106\x12\x11\n" +
	"\rESP32_S3_PICO\x107\x12\r\n" +
	"\tCHATTER_2\x108\x12\x1e\n" +
	"\x1aHELTEC_WIRELESS_PAPER_V1_0\x109\x12 \n" +
	"\x1cHELTEC_WIRELESS_TRACKER_V1_0\x10:\x12\v\n" +
	"\aUNPHONE\x10;\x12\f\n" +
	"\bTD_LORAC\x10<\x12\x13\n" +
	"\x0fCDEBYTE_EORA_S3\x10=\x12\x0f\n" +
	"\vTWC_MESH_V4\x10>\x12\x16\n" +
	"\x12NRF52_PROMICRO_DIY\x10?\x12\x1f\n" +
	"\x1bRADIOMASTER_900_BANDIT_NANO\x10@\x12\x1c\n" +
	"\x18HELTEC_CAPSULE_SENSOR_V3\x10A\x12\x1d\n" +
	"\x19HELTEC_VISION_MASTER_T190\x10B\x12\x1d\n" +
	"\x19HELTEC_VISION_MASTER_E213\x10C\x12\x1d\n" +
	"\x19HELTEC_VISION_MASTER_E290\x10D\x12\x19\n" +
	"\x15HELTEC_MESH_NODE_T114\x10E\x12\x16\n" +
	"\x12SENSECAP_INDICATOR\x10F\x12\x13\n" +
	"\x0fTRACKER_T1000_E\x10G\x12\v\n" +
	"\aRAK3172\x10H\x12\n" +
	"\n" +
	"\x06WIO_E5\x10I\x12\x1a\n" +
	"\x16RADIOMASTER_900_BANDIT\x10J\x12\x0f\n" +
	"\n" +
	"PRIVATE_HW\x10\xff\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_mesh_proto_rawDescOnce sync.Once
	file_mesh_proto_rawDescData []byte
)

func file_mesh_proto_rawDescGZIP() []byte {
	file_mesh_proto_rawDescOnce.Do(func() {
		file_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)))
	})
	return file_mesh_proto_rawDescData
}

var file_mesh_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mesh_proto_goTypes = []any{
	(HardwareModel)(0),      // 0: meshtastic.HardwareModel
	(Position_LocSource)(0), // 1: meshtastic.Position.LocSource
	(Position_AltSource)(0), // 2: meshtastic.Position.AltSource
	(*Position)(nil),        // 3: meshtastic.Position
}
var file_mesh_proto_depIdxs = []int32{
	1, // 0: meshtastic.Position.location_source:type_name -> meshtastic.Position.LocSource
	2, // 1: meshtastic.Position.altitude_source:type_name -> meshtastic.Position.AltSource
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mesh_proto_init() }
func file_mesh_proto_init() {
	if File_mesh_proto != nil {
		return
	}
	file_mesh_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mesh_proto_goTypes,
		DependencyIndexes: file_mesh_proto_depIdxs,
		EnumInfos:         file_mesh_proto_enumTypes,
		MessageInfos:      file_mesh_proto_msgTypes,
	}.Build()
	File_mesh_proto = out.File
	file_mesh_proto_goTypes = nil
	file_mesh_proto_depIdxs = nil
}
