// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.3
// source: telemetry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BatteryLevel       uint32                 `protobuf:"varint,1,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	Voltage            float32                `protobuf:"fixed32,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	ChannelUtilization float32                `protobuf:"fixed32,3,opt,name=channel_utilization,json=channelUtilization,proto3" json:"channel_utilization,omitempty"`
	AirUtilTx          float32                `protobuf:"fixed32,4,opt,name=air_util_tx,json=airUtilTx,proto3" json:"air_util_tx,omitempty"`
	UptimeSeconds      uint32                 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeviceMetrics) Reset() {
	*x = DeviceMetrics{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceMetrics) ProtoMessage() {}

func (x *DeviceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceMetrics.ProtoReflect.Descriptor instead.
func (*DeviceMetrics) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceMetrics) GetBatteryLevel() uint32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *DeviceMetrics) GetVoltage() float32 {
	if x != nil {
		return x.Voltage
	}
	return 0
}

func (x *DeviceMetrics) GetChannelUtilization() float32 {
	if x != nil {
		return x.ChannelUtilization
	}
	return 0
}

func (x *DeviceMetrics) GetAirUtilTx() float32 {
	if x != nil {
		return x.AirUtilTx
	}
	return 0
}

func (x *DeviceMetrics) GetUptimeSeconds() uint32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type EnvironmentMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Temperature        float32                `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	RelativeHumidity   float32                `protobuf:"fixed32,2,opt,name=relative_humidity,json=relativeHumidity,proto3" json:"relative_humidity,omitempty"`
	BarometricPressure float32                `protobuf:"fixed32,3,opt,name=barometric_pressure,json=barometricPressure,proto3" json:"barometric_pressure,omitempty"`
	GasResistance      float32                `protobuf:"fixed32,4,opt,name=gas_resistance,json=gasResistance,proto3" json:"gas_resistance,omitempty"`
	Voltage            float32                `protobuf:"fixed32,5,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Current            float32                `protobuf:"fixed32,6,opt,name=current,proto3" json:"current,omitempty"`
	Iaq                uint32                 `protobuf:"varint,7,opt,name=iaq,proto3" json:"iaq,omitempty"`
	Distance           float32                `protobuf:"fixed32,8,opt,name=distance,proto3" json:"distance,omitempty"`
	Lux                float32                `protobuf:"fixed32,9,opt,name=lux,proto3" json:"lux,omitempty"`
	WhiteLux           float32                `protobuf:"fixed32,10,opt,name=white_lux,json=whiteLux,proto3" json:"white_lux,omitempty"`
	IrLux              float32                `protobuf:"fixed32,11,opt,name=ir_lux,json=irLux,proto3" json:"ir_lux,omitempty"`
	UvLux              float32                `protobuf:"fixed32,12,opt,name=uv_lux,json=uvLux,proto3" json:"uv_lux,omitempty"`
	WindDirection      uint32                 `protobuf:"varint,13,opt,name=wind_direction,json=windDirection,proto3" json:"wind_direction,omitempty"`
	WindSpeed          float32                `protobuf:"fixed32,14,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"`
	Weight             float32                `protobuf:"fixed32,15,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnvironmentMetrics) Reset() {
	*x = EnvironmentMetrics{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentMetrics) ProtoMessage() {}

func (x *EnvironmentMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentMetrics.ProtoReflect.Descriptor instead.
func (*EnvironmentMetrics) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *EnvironmentMetrics) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *EnvironmentMetrics) GetRelativeHumidity() float32 {
	if x != nil {
		return x.RelativeHumidity
	}
	return 0
}

func (x *EnvironmentMetrics) GetBarometricPressure() float32 {
	if x != nil {
		return x.BarometricPressure
	}
	return 0
}

func (x *EnvironmentMetrics) GetGasResistance() float32 {
	if x != nil {
		return x.GasResistance
	}
	return 0
}

func (x *EnvironmentMetrics) GetVoltage() float32 {
	if x != nil {
		return x.Voltage
	}
	return 0
}

func (x *EnvironmentMetrics) GetCurrent() float32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *EnvironmentMetrics) GetIaq() uint32 {
	if x != nil {
		return x.Iaq
	}
	return 0
}

func (x *EnvironmentMetrics) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *EnvironmentMetrics) GetLux() float32 {
	if x != nil {
		return x.Lux
	}
	return 0
}

func (x *EnvironmentMetrics) GetWhiteLux() float32 {
	if x != nil {
		return x.WhiteLux
	}
	return 0
}

func (x *EnvironmentMetrics) GetIrLux() float32 {
	if x != nil {
		return x.IrLux
	}
	return 0
}

func (x *EnvironmentMetrics) GetUvLux() float32 {
	if x != nil {
		return x.UvLux
	}
	return 0
}

func (x *EnvironmentMetrics) GetWindDirection() uint32 {
	if x != nil {
		return x.WindDirection
	}
	return 0
}

func (x *EnvironmentMetrics) GetWindSpeed() float32 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *EnvironmentMetrics) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type AirQualityMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Pm10Standard       uint32                 `protobuf:"varint,1,opt,name=pm10_standard,json=pm10Standard,proto3" json:"pm10_standard,omitempty"`
	Pm25Standard       uint32                 `protobuf:"varint,2,opt,name=pm25_standard,json=pm25Standard,proto3" json:"pm25_standard,omitempty"`
	Pm100Standard      uint32                 `protobuf:"varint,3,opt,name=pm100_standard,json=pm100Standard,proto3" json:"pm100_standard,omitempty"`
	Pm10Environmental  uint32                 `protobuf:"varint,4,opt,name=pm10_environmental,json=pm10Environmental,proto3" json:"pm10_environmental,omitempty"`
	Pm25Environmental  uint32                 `protobuf:"varint,5,opt,name=pm25_environmental,json=pm25Environmental,proto3" json:"pm25_environmental,omitempty"`
	Pm100Environmental uint32                 `protobuf:"varint,6,opt,name=pm100_environmental,json=pm100Environmental,proto3" json:"pm100_environmental,omitempty"`
	Particles_03Um     uint32                 `protobuf:"varint,7,opt,name=particles_03um,json=particles03um,proto3" json:"particles_03um,omitempty"`
	Particles_05Um     uint32                 `protobuf:"varint,8,opt,name=particles_05um,json=particles05um,proto3" json:"particles_05um,omitempty"`
	Particles_10Um     uint32                 `protobuf:"varint,9,opt,name=particles_10um,json=particles10um,proto3" json:"particles_10um,omitempty"`
	Particles_25Um     uint32                 `protobuf:"varint,10,opt,name=particles_25um,json=particles25um,proto3" json:"particles_25um,omitempty"`
	Particles_50Um     uint32                 `protobuf:"varint,11,opt,name=particles_50um,json=particles50um,proto3" json:"particles_50um,omitempty"`
	Particles_100Um    uint32                 `protobuf:"varint,12,opt,name=particles_100um,json=particles100um,proto3" json:"particles_100um,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AirQualityMetrics) Reset() {
	*x = AirQualityMetrics{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirQualityMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirQualityMetrics) ProtoMessage() {}

func (x *AirQualityMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirQualityMetrics.ProtoReflect.Descriptor instead.
func (*AirQualityMetrics) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *AirQualityMetrics) GetPm10Standard() uint32 {
	if x != nil {
		return x.Pm10Standard
	}
	return 0
}

func (x *AirQualityMetrics) GetPm25Standard() uint32 {
	if x != nil {
		return x.Pm25Standard
	}
	return 0
}

func (x *AirQualityMetrics) GetPm100Standard() uint32 {
	if x != nil {
		return x.Pm100Standard
	}
	return 0
}

func (x *AirQualityMetrics) GetPm10Environmental() uint32 {
	if x != nil {
		return x.Pm10Environmental
	}
	return 0
}

func (x *AirQualityMetrics) GetPm25Environmental() uint32 {
	if x != nil {
		return x.Pm25Environmental
	}
	return 0
}

func (x *AirQualityMetrics) GetPm100Environmental() uint32 {
	if x != nil {
		return x.Pm100Environmental
	}
	return 0
}

func (x *AirQualityMetrics) GetParticles_03Um() uint32 {
	if x != nil {
		return x.Particles_03Um
	}
	return 0
}

func (x *AirQualityMetrics) GetParticles_05Um() uint32 {
	if x != nil {
		return x.Particles_05Um
	}
	return 0
}

func (x *AirQualityMetrics) GetParticles_10Um() uint32 {
	if x != nil {
		return x.Particles_10Um
	}
	return 0
}

func (x *AirQualityMetrics) GetParticles_25Um() uint32 {
	if x != nil {
		return x.Particles_25Um
	}
	return 0
}

func (x *AirQualityMetrics) GetParticles_50Um() uint32 {
	if x != nil {
		return x.Particles_50Um
	}
	return 0
}

func (x *AirQualityMetrics) GetParticles_100Um() uint32 {
	if x != nil {
		return x.Particles_100Um
	}
	return 0
}

type PowerMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ch1Voltage    float32                `protobuf:"fixed32,1,opt,name=ch1_voltage,json=ch1Voltage,proto3" json:"ch1_voltage,omitempty"`
	Ch1Current    float32                `protobuf:"fixed32,2,opt,name=ch1_current,json=ch1Current,proto3" json:"ch1_current,omitempty"`
	Ch2Voltage    float32                `protobuf:"fixed32,3,opt,name=ch2_voltage,json=ch2Voltage,proto3" json:"ch2_voltage,omitempty"`
	Ch2Current    float32                `protobuf:"fixed32,4,opt,name=ch2_current,json=ch2Current,proto3" json:"ch2_current,omitempty"`
	Ch3Voltage    float32                `protobuf:"fixed32,5,opt,name=ch3_voltage,json=ch3Voltage,proto3" json:"ch3_voltage,omitempty"`
	Ch3Current    float32                `protobuf:"fixed32,6,opt,name=ch3_current,json=ch3Current,proto3" json:"ch3_current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerMetrics) Reset() {
	*x = PowerMetrics{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerMetrics) ProtoMessage() {}

func (x *PowerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerMetrics.ProtoReflect.Descriptor instead.
func (*PowerMetrics) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *PowerMetrics) GetCh1Voltage() float32 {
	if x != nil {
		return x.Ch1Voltage
	}
	return 0
}

func (x *PowerMetrics) GetCh1Current() float32 {
	if x != nil {
		return x.Ch1Current
	}
	return 0
}

func (x *PowerMetrics) GetCh2Voltage() float32 {
	if x != nil {
		return x.Ch2Voltage
	}
	return 0
}

func (x *PowerMetrics) GetCh2Current() float32 {
	if x != nil {
		return x.Ch2Current
	}
	return 0
}

func (x *PowerMetrics) GetCh3Voltage() float32 {
	if x != nil {
		return x.Ch3Voltage
	}
	return 0
}

func (x *PowerMetrics) GetCh3Current() float32 {
	if x != nil {
		return x.Ch3Current
	}
	return 0
}

type Telemetry struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Time               uint32                 `protobuf:"fixed32,1,opt,name=time,proto3" json:"time,omitempty"`
	DeviceMetrics      *DeviceMetrics         `protobuf:"bytes,2,opt,name=device_metrics,json=deviceMetrics,proto3,oneof" json:"device_metrics,omitempty"`
	EnvironmentMetrics *EnvironmentMetrics    `protobuf:"bytes,3,opt,name=environment_metrics,json=environmentMetrics,proto3,oneof" json:"environment_metrics,omitempty"`
	AirQualityMetrics  *AirQualityMetrics     `protobuf:"bytes,4,opt,name=air_quality_metrics,json=airQualityMetrics,proto3,oneof" json:"air_quality_metrics,omitempty"`
	PowerMetrics       *PowerMetrics          `protobuf:"bytes,5,opt,name=power_metrics,json=powerMetrics,proto3,oneof" json:"power_metrics,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *Telemetry) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Telemetry) GetDeviceMetrics() *DeviceMetrics {
	if x != nil {
		return x.DeviceMetrics
	}
	return nil
}

func (x *Telemetry) GetEnvironmentMetrics() *EnvironmentMetrics {
	if x != nil {
		return x.EnvironmentMetrics
	}
	return nil
}

func (x *Telemetry) GetAirQualityMetrics() *AirQualityMetrics {
	if x != nil {
		return x.AirQualityMetrics
	}
	return nil
}

func (x *Telemetry) GetPowerMetrics() *PowerMetrics {
	if x != nil {
		return x.PowerMetrics
	}
	return nil
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\n" +
	"meshtastic\"\xc6\x01\n" +
	"\rDeviceMetrics\x12#\n" +
	"\rbattery_level\x18\x01 \x01(\rR\fbatteryLevel\x12\x18\n" +
	"\avoltage\x18\x02 \x01(\x02R\avoltage\x12/\n" +
	"\x13channel_utilization\x18\x03 \x01(\x02R\x12channelUtilization\x12\x1e\n" +
	"\vair_util_tx\x18\x04 \x01(\x02R\tairUtilTx\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\rR\ruptimeSeconds\"\xd8\x03\n" +
	"\x12EnvironmentMetrics\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x02R\vtemperature\x12+\n" +
	"\x11relative_humidity\x18\x02 \x01(\x02R\x10relativeHumidity\x12/\n" +
	"\x13barometric_pressure\x18\x03 \x01(\x02R\x12barometricPressure\x12%\n" +
	"\x0egas_resistance\x18\x04 \x01(\x02R\rgasResistance\x12\x18\n" +
	"\avoltage\x18\x05 \x01(\x02R\avoltage\x12\x18\n" +
	"\acurrent\x18\x06 \x01(\x02R\acurrent\x12\x10\n" +
	"\x03iaq\x18\a \x01(\rR\x03iaq\x12\x1a\n" +
	"\bdistance\x18\b \x01(\x02R\bdistance\x12\x10\n" +
	"\x03lux\x18\t \x01(\x02R\x03lux\x12\x1b\n" +
	"\twhite_lux\x18\n" +
	" \x01(\x02R\bwhiteLux\x12\x15\n" +
	"\x06ir_lux\x18\v \x01(\x02R\x05irLux\x12\x15\n" +
	"\x06uv_lux\x18\f \x01(\x02R\x05uvLux\x12%\n" +
	"\x0ewind_direction\x18\r \x01(\rR\rwindDirection\x12\x1d\n" +
	"\n" +
	"wind_speed\x18\x0e \x01(\x02R\twindSpeed\x12\x16\n" +
	"\x06weight\x18\x0f \x01(\x02R\x06weight\"\xff\x03\n" +
	"\x11AirQualityMetrics\x12#\n" +
	"\rpm10_standard\x18\x01 \x01(\rR\fpm10Standard\x12#\n" +
	"\rpm25_standard\x18\x02 \x01(\rR\fpm25Standard\x12%\n" +
	"\x0epm100_standard\x18\x03 \x01(\rR\rpm100Standard\x12-\n" +
	"\x12pm10_environmental\x18\x04 \x01(\rR\x11pm10Environmental\x12-\n" +
	"\x12pm25_environmental\x18\x05 \x01(\rR\x11pm25Environmental\x12/\n" +
	"\x13pm100_environmental\x18\x06 \x01(\rR\x12pm100Environmental\x12%\n" +
	"\x0eparticles_03um\x18\a \x01(\rR\rparticles03um\x12%\n" +
	"\x0eparticles_05um\x18\b \x01(\rR\rparticles05um\x12%\n" +
	"\x0eparticles_10um\x18\t \x01(\rR\rparticles10um\x12%\n" +
	"\x0eparticles_25um\x18\n" +
	" \x01(\rR\rparticles25um\x12%\n" +
	"\x0eparticles_50um\x18\v \x01(\rR\rparticles50um\x12'\n" +
	"\x0fparticles_100um\x18\f \x01(\rR\x0eparticles100um\"\xd4\x01\n" +
	"\fPowerMetrics\x12\x1f\n" +
	"\vch1_voltage\x18\x01 \x01(\x02R\n" +
	"ch1Voltage\x12\x1f\n" +
	"\vch1_current\x18\x02 \x01(\x02R\n" +
	"ch1Current\x12\x1f\n" +
	"\vch2_voltage\x18\x03 \x01(\x02R\n" +
	"ch2Voltage\x12\x1f\n" +
	"\vch2_current\x18\x04 \x01(\x02R\n" +
	"ch2Current\x12\x1f\n" +
	"\vch3_voltage\x18\x05 \x01(\x02R\n" +
	"ch3Voltage\x12\x1f\n" +
	"\vch3_current\x18\x06 \x01(\x02R\n" +
	"ch3Current\"\xa9\x03\n" +
	"\tTelemetry\x12\x12\n" +
	"\x04time\x18\x01 \x01(\aR\x04time\x12E\n" +
	"\x0edevice_metrics\x18\x02 \x01(\v2\x19.meshtastic.DeviceMetricsH\x00R\rdeviceMetrics\x88\x01\x01\x12T\n" +
	"\x13environment_metrics\x18\x03 \x01(\v2\x1e.meshtastic.EnvironmentMetricsH\x01R\x12environmentMetrics\x88\x01\x01\x12R\n" +
	"\x13air_quality_metrics\x18\x04 \x01(\v2\x1d.meshtastic.AirQualityMetricsH\x02R\x11airQualityMetrics\x88\x01\x01\x12B\n" +
	"\rpower_metrics\x18\x05 \x01(\v2\x18.meshtastic.PowerMetricsH\x03R\fpowerMetrics\x88\x01\x01B\x11\n" +
	"\x0f_device_metricsB\x16\n" +
	"\x14_environment_metricsB\x16\n" +
	"\x14_air_quality_metricsB\x10\n" +
	"\x0e_power_metricsB\x06Z\x04./pbb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_telemetry_proto_goTypes = []any{
	(*DeviceMetrics)(nil),      // 0: meshtastic.DeviceMetrics
	(*EnvironmentMetrics)(nil), // 1: meshtastic.EnvironmentMetrics
	(*AirQualityMetrics)(nil),  // 2: meshtastic.AirQualityMetrics
	(*PowerMetrics)(nil),       // 3: meshtastic.PowerMetrics
	(*Telemetry)(nil),          // 4: meshtastic.Telemetry
}
var file_telemetry_proto_depIdxs = []int32{
	0, // 0: meshtastic.Telemetry.device_metrics:type_name -> meshtastic.DeviceMetrics
	1, // 1: meshtastic.Telemetry.environment_metrics:type_name -> meshtastic.EnvironmentMetrics
	2, // 2: meshtastic.Telemetry.air_quality_metrics:type_name -> meshtastic.AirQualityMetrics
	3, // 3: meshtastic.Telemetry.power_metrics:type_name -> meshtastic.PowerMetrics
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	file_telemetry_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
